# Sidebar navigation

- label: 'Presentaci贸n'
  link: '/'
- label: 'Generalidades'
  items:
    - label: 'Conceptos b谩sicos'
      link: '/generalidades/conceptos-basicos'
    - label: 'Marco legal'
      link: '/generalidades/marco-legal'
    - label: 'Estructura b谩sica'
      link: '/generalidades/estructura-basica'
- label: 'Estructura financiera'
  items:
    - label: 'Estado de situaci贸n financiera'
      link: '/estructura-financiera/estado-situacion-financiera'
    - label: 'Estado de resultados'
      link: '/estructura-financiera/estado-resultados'
    - label: 'Activo, pasivo y capital'
      link: '/estructura-financiera/activo-pasivo-capital'
- label: 'Mercanc铆as'
  items:
    - label: 'Procedimiento global'
      link: '/mercancias/procedimiento-global'
    - label: 'Procedimiento anal铆tico'
      link: '/mercancias/procedimiento-analitico'
    - label: 'Inventarios perpetuos'
      link: '/mercancias/inventarios-perpetuos'
- label: 'Libros contables'
  items:
    - label: 'Diario continental'
      link: '/libros-contables/diario-continental'
    - label: 'Diario tabular'
      link: '/libros-contables/diario-tabular'
    - label: 'M茅todo de p贸lizas'
      link: '/libros-contables/metodo-polizas'
- label: 'Costo de ventas'
  items:
    - label: 'M茅todos de valuaci贸n'
      link: '/costo-ventas/valuacion'
- label: Hoja de trabajo
  items:
    - label: 'Ajustes'
      link: '/hoja-trabajo/ajustes'
    - label: 'Hoja de trabajo'
      link: '/hoja-trabajo/hoja-trabajo'
- label: 'Comunidad'
  items:
    - label: 'Discord'
      link: 'https://discord.gg/vpWTZMe9wK'
    - label: 'Instagram'
      link: 'https://instagram.com/todoconta'
    - label: 'Twitter'
      link: 'https://twitter.com/todoconta'
    - label: 'Facebook'
      link: 'https://facebook.com/todoconta'
    - label: 'Donar '
      link: 'https://todoconta.com/donar'